version: "3"
services:
  proxy:
    image: rsrp/caddy-cloudflare:2.6.1
    restart: unless-stopped
    network_mode: host
    environment:
      CLOUDFLARE_API_TOKEN: ${PROXY_CLOUDFLARE_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ${PROXY_DATA}:/data
