version: "3"
services:
  homeassistant:
    image: homeassistant/home-assistant:2022.9.7
    restart: unless-stopped
    environment:
      TZ: Europe/Stockholm
    network_mode: host
    volumes:
      - ${HOMEASSISTANT_DATA}/config:/config
